<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="CHENNENGJI"><DocLocation><![CDATA[D:\Counter\Script\Counter]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Counter]]></DName>
<Res><![CDATA[Counter]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run "D:\Counter\Script\Counter\Counter.jar",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "D:\Counter\Script\Counter\Counter.jar",1]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "D:\Counter\Script\Counter\Counter.jar",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[计算器]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="13" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[1.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[1.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="17" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[+.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="19" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[+.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="21" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[1.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="23" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[1.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="25" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[=.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="27" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[=.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="29" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA[检查结果正确]]></Obj>
<Details ><![CDATA[检查结果正确]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="User" icon="7" nRep="30" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[检查结果正确]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[C.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="32" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[C.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="34" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="36" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="38" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[*.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="40" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[*.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="42" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="44" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="46" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[=.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="48" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[=.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="50" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[检查结果正确]]></Obj>
<Details ><![CDATA[检查结果正确]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="User" icon="7" nRep="51" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[检查结果正确]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[C.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="53" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[C.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="55" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[1.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:32]]></Time>
<TimeTick>1274424932</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="57" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[1.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[0.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="59" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[0.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="61" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[/.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="63" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[/.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="65" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="67" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="69" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[=.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="71" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[=.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="73" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[检查结果正确]]></Obj>
<Details ><![CDATA[检查结果正确]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="User" icon="7" nRep="74" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[检查结果正确]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[C.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="76" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[C.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="78" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[1.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="80" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[1.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="82" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="84" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[MS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="86" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[MS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="88" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[MR.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="90" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[MR.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="92" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[检查结果正确]]></Obj>
<Details ><![CDATA[检查结果正确]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="User" icon="7" nRep="93" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[检查结果正确]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[C.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="95" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[C.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="97" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[1.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="99" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[1.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="101" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="103" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj ><![CDATA[检查结果正确]]></Obj>
<Details ><![CDATA[检查结果正确]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="User" icon="7" nRep="104" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[检查结果正确]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[C.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="106" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[C.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="108" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="110" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[..Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="112" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[..Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[5.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="114" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[5.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="116" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[*.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="118" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[*.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="120" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[4.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="122" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[4.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[5.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="124" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[5.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="126" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[/.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="128" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[/.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="130" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[8.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="132" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[8.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="134" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[=.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="136" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[=.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="138" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj ><![CDATA[检查结果正确]]></Obj>
<Details ><![CDATA[检查结果正确]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="User" icon="7" nRep="139" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[检查结果正确]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[C.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="141" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[C.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[计算器.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="143" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[计算器.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[4.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2010-05-21 - 14:55:33]]></Time>
<TimeTick>1274424933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="145" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[4.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77">