<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED>

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Action*,Summary?,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,NodeArgs) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="QuickTest Professional" productVer="9.2" os="Windows XP" host="THORWATH"><DocLocation><![CDATA[C:\QTP\Scripts\dt2\BAT\suiteControl]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[suiteControl]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[main]]></AName>
<Action rID="T5">
<AName><![CDATA[main [Test005 Walk Screens]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Security]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:33]]></Time>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Security.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:33]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="11" >
<Disp><![CDATA[Security.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="10" >
<Disp><![CDATA[Security]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Exception]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:33]]></Time>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Exception.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:33]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="14" >
<Disp><![CDATA[Exception.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="13" >
<Disp><![CDATA[Exception]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[dt2App]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:33]]></Time>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[wAuthorize]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:33]]></Time>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[wAuthorize.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:33]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="18" >
<Disp><![CDATA[wAuthorize.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="17" >
<Disp><![CDATA[wAuthorize]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[wHelp.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:33]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="20" >
<Disp><![CDATA[wHelp.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[dt2App.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:33]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="21" >
<Disp><![CDATA[dt2App.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[dt2App.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:33]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="22" >
<Disp><![CDATA[dt2App.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[pbMainWin.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:33]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="23" >
<Disp><![CDATA[pbMainWin.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[pbMainWin.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", True, True, 10000]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:34]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="27" >
<Disp><![CDATA[pbMainWin.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[pbMainWin.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:34]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="29" >
<Disp><![CDATA[pbMainWin.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[pbWhatsNew.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:35]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="30" >
<Disp><![CDATA[pbWhatsNew.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[pbWhatsNew.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", True, True, 10000]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:36]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="34" >
<Disp><![CDATA[pbWhatsNew.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[pbWhatsNew.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:36]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="36" >
<Disp><![CDATA[pbWhatsNew.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" >
<Disp><![CDATA[dt2App]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Security]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:36]]></Time>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Security.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:36]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="39" >
<Disp><![CDATA[Security.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="38" >
<Disp><![CDATA[Security]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Exception]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:36]]></Time>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Exception.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:36]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="42" >
<Disp><![CDATA[Exception.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="41" >
<Disp><![CDATA[Exception]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[dt2App]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:36]]></Time>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[wAuthorize]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:36]]></Time>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[wAuthorize.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:36]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="46" >
<Disp><![CDATA[wAuthorize.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="45" >
<Disp><![CDATA[wAuthorize]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[wHelp.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:36]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="48" >
<Disp><![CDATA[wHelp.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[dt2App.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:36]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="49" >
<Disp><![CDATA[dt2App.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[dt2App.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:36]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="50" >
<Disp><![CDATA[dt2App.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[pbHelp.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:36]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="51" >
<Disp><![CDATA[pbHelp.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[pbHelp.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", True, True, 10000]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:37]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="55" >
<Disp><![CDATA[pbHelp.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[pbHelp.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:37]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="57" >
<Disp><![CDATA[pbHelp.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[wHelp.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:37]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="58" >
<Disp><![CDATA[wHelp.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[wHelp.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", True, True, 10000]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:38]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="62" >
<Disp><![CDATA[wHelp.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="44" >
<Disp><![CDATA[dt2App]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj ><![CDATA[test005 walkScreens(), nav.invokeScreen(), nav.verScreen()]]></Obj>
<Details ><![CDATA['dt2.Help' verifyArray(0) object, 'wHelp window  native class:Window  ', verify passed
]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:38]]></Time>
<NodeArgs eType="User" icon="10" nRep="63" >
<Disp><![CDATA[test005 walkScreens(), nav.invokeScreen(), nav.verScreen()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ Digital Technician II Online Help ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:38]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="64" >
<Disp><![CDATA[[ Digital Technician II Online Help ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ Digital Technician II Online Help ].Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:38]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="66" >
<Disp><![CDATA[[ Digital Technician II Online Help ].Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:39]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="68" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[test005 walkScreens(), nav.dismissHelp()]]></Obj>
<Details ><![CDATA[DT2 Help dialog was dismissed]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:39]]></Time>
<NodeArgs eType="User" icon="10" nRep="69" >
<Disp><![CDATA[test005 walkScreens(), nav.dismissHelp()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Security]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:40]]></Time>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Security.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:40]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="72" >
<Disp><![CDATA[Security.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="71" >
<Disp><![CDATA[Security]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Exception]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:40]]></Time>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Exception.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:40]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="75" >
<Disp><![CDATA[Exception.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="74" >
<Disp><![CDATA[Exception]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[dt2App]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:40]]></Time>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[wAuthorize]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:40]]></Time>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[wAuthorize.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:40]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="79" >
<Disp><![CDATA[wAuthorize.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="78" >
<Disp><![CDATA[wAuthorize]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[wHelp.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:40]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="81" >
<Disp><![CDATA[wHelp.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[dt2App.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:40]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="82" >
<Disp><![CDATA[dt2App.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[dt2App.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:40]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="83" >
<Disp><![CDATA[dt2App.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[pbToolbox.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:40]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="84" >
<Disp><![CDATA[pbToolbox.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[pbToolbox.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", True, True, 10000]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:41]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="88" >
<Disp><![CDATA[pbToolbox.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[pbToolbox.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:41]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="90" >
<Disp><![CDATA[pbToolbox.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[pbFaultCode.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:41]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="91" >
<Disp><![CDATA[pbFaultCode.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[pbFaultCode.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", True, True, 10000]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:42]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="95" >
<Disp><![CDATA[pbFaultCode.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[pbDataItems.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:42]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="96" >
<Disp><![CDATA[pbDataItems.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[pbDataItems.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", True, True, 10000]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:43]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="100" >
<Disp><![CDATA[pbDataItems.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="77" >
<Disp><![CDATA[dt2App]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[test005 walkScreens(), nav.invokeScreen(), nav.verScreen()]]></Obj>
<Details ><![CDATA['dt2.Toolbox' verifyArray(0) object, 'pbFaultCode button  native class:SwfButton  ', verify passed
'dt2.Toolbox' verifyArray(1) object, 'pbDataItems button  native class:SwfButton  ', verify passed
]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:43]]></Time>
<NodeArgs eType="User" icon="10" nRep="101" >
<Disp><![CDATA[test005 walkScreens(), nav.invokeScreen(), nav.verScreen()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Security]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:43]]></Time>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Security.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:43]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="104" >
<Disp><![CDATA[Security.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="103" >
<Disp><![CDATA[Security]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Exception]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:43]]></Time>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Exception.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:43]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="107" >
<Disp><![CDATA[Exception.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="106" >
<Disp><![CDATA[Exception]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[dt2App]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:43]]></Time>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[wAuthorize]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:43]]></Time>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[wAuthorize.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:43]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="111" >
<Disp><![CDATA[wAuthorize.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="110" >
<Disp><![CDATA[wAuthorize]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[wHelp.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:43]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="113" >
<Disp><![CDATA[wHelp.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[dt2App.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:43]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="114" >
<Disp><![CDATA[dt2App.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[dt2App.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:43]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="115" >
<Disp><![CDATA[dt2App.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[pbVehicleSelect.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:43]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="116" >
<Disp><![CDATA[pbVehicleSelect.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[pbVehicleSelect.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", True, True, 10000]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:44]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="120" >
<Disp><![CDATA[pbVehicleSelect.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[pbVehicleSelect.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:45]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="122" >
<Disp><![CDATA[pbVehicleSelect.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[sVIN.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:45]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="123" >
<Disp><![CDATA[sVIN.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[sVIN.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", True, True, 10000]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="127" >
<Disp><![CDATA[sVIN.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="109" >
<Disp><![CDATA[dt2App]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj ><![CDATA[test005 walkScreens(), nav.invokeScreen(), nav.verScreen()]]></Obj>
<Details ><![CDATA['dt2.VehicleSelect' verifyArray(0) object, 'sVIN edit box  native class:SwfEdit  ', verify passed
]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<NodeArgs eType="User" icon="10" nRep="128" >
<Disp><![CDATA[test005 walkScreens(), nav.invokeScreen(), nav.verScreen()]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[Security]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[Security.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="131" >
<Disp><![CDATA[Security.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="130" >
<Disp><![CDATA[Security]]></Disp>
</NodeArgs>
</Step>
<Step rID="T78">
<Obj plainTxt="False" ><![CDATA[Exception]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<Step rID="T79">
<Obj plainTxt="False" ><![CDATA[Exception.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="134" >
<Disp><![CDATA[Exception.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="133" >
<Disp><![CDATA[Exception]]></Disp>
</NodeArgs>
</Step>
<Step rID="T80">
<Obj plainTxt="False" ><![CDATA[dt2App]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<Step rID="T81">
<Obj plainTxt="False" ><![CDATA[wAuthorize]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<Step rID="T82">
<Obj plainTxt="False" ><![CDATA[wAuthorize.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="138" >
<Disp><![CDATA[wAuthorize.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="137" >
<Disp><![CDATA[wAuthorize]]></Disp>
</NodeArgs>
</Step>
<Step rID="T83">
<Obj plainTxt="False" ><![CDATA[wHelp.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="140" >
<Disp><![CDATA[wHelp.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T84">
<Obj plainTxt="False" ><![CDATA[dt2App.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="141" >
<Disp><![CDATA[dt2App.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T85">
<Obj plainTxt="False" ><![CDATA[dt2App.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="142" >
<Disp><![CDATA[dt2App.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="136" >
<Disp><![CDATA[dt2App]]></Disp>
</NodeArgs>
</Step>
<Step rID="T86">
<Obj plainTxt="False" ><![CDATA[Security]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<Step rID="T87">
<Obj plainTxt="False" ><![CDATA[Security.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="145" >
<Disp><![CDATA[Security.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="144" >
<Disp><![CDATA[Security]]></Disp>
</NodeArgs>
</Step>
<Step rID="T88">
<Obj plainTxt="False" ><![CDATA[Exception]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<Step rID="T89">
<Obj plainTxt="False" ><![CDATA[Exception.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="148" >
<Disp><![CDATA[Exception.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="147" >
<Disp><![CDATA[Exception]]></Disp>
</NodeArgs>
</Step>
<Step rID="T90">
<Obj plainTxt="False" ><![CDATA[dt2App]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<Step rID="T91">
<Obj plainTxt="False" ><![CDATA[wAuthorize]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<Step rID="T92">
<Obj plainTxt="False" ><![CDATA[wAuthorize.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/1/2007 - 13:57:46]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="152" >